# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mail-Digest-Tools
version:      2.05
version_from: Tools.pm
installdirs:  site
requires:
    List::Compare:                 0.15

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
